### ISSUE TITLE
update fucked up goblin set

### ISSUE THREAD

**Issue by aerith1984** [KiuviGonka/Card-Switch#1]
update fucked up goblin set

**Comment by KiuviGonka** [comment]
What DO you mean?

**Comment by aerith1984** [comment]
goblin doent work as command and if u die itss sets on its own to goblin

**Comment by KiuviGonka** [comment]
True, but unotice that goblin gone when u get rest? It's a new functionality now goblin put on when u die and come back to dos when u rest
